# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 06:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('ID_Appointment', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('ID_Bill', models.AutoField(primary_key=True, serialize=False)),
                ('Owes', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ID_Appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('ID_Diagnostic', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('ID_Appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('ID_Medic', models.AutoField(primary_key=True, serialize=False)),
                ('Speciality', models.CharField(max_length=25)),
                ('Prof_License', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Non_Pathological_History',
            fields=[
                ('ID_Non_Pathological', models.AutoField(primary_key=True, serialize=False)),
                ('Hypertension', models.BooleanField()),
                ('Hypotension', models.BooleanField()),
                ('Diabetes', models.BooleanField()),
                ('Hepatitis', models.BooleanField()),
                ('Tuberculosis', models.BooleanField()),
                ('Complications', models.BooleanField()),
                ('Trouble_Breathing', models.BooleanField()),
                ('Alcohol', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pathological_History',
            fields=[
                ('ID_Pathological', models.AutoField(primary_key=True, serialize=False)),
                ('Actual_Threatment', models.BooleanField()),
                ('Actual_Medicine', models.BooleanField()),
                ('Allergies', models.BooleanField()),
                ('Anestesic_Reaction', models.BooleanField()),
                ('Hemorrhages', models.BooleanField()),
                ('Complications', models.BooleanField()),
                ('Angina_Pectoris', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('ID_Patient', models.AutoField(primary_key=True, serialize=False)),
                ('Marital_Status', models.CharField(max_length=25)),
                ('Ocupation', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Teeths',
            fields=[
                ('ID_Teeths', models.AutoField(primary_key=True, serialize=False)),
                ('Number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(85)])),
            ],
        ),
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('ID_Treatments', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('Cost', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Treatments_Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Appointment')),
                ('ID_Teeths', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Teeths')),
                ('ID_Treatments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Treatments')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ID_Users', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('Last_Name', models.CharField(max_length=25)),
                ('Age', models.DateField(default=django.utils.timezone.now)),
                ('Sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('Mail', models.EmailField(max_length=254)),
                ('Phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='ID_Users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Users'),
        ),
        migrations.AddField(
            model_name='pathological_history',
            name='ID_Users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Users'),
        ),
        migrations.AddField(
            model_name='non_pathological_history',
            name='ID_Users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Users'),
        ),
        migrations.AddField(
            model_name='medic',
            name='ID_Users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Users'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ID_Medic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Medic'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ID_Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Patient'),
        ),
    ]
